name: composite-action-demo

on:
  push:
    branches: [main]

jobs: 
    greet:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Run composite action
              id: greet
              uses: ./.github/actions/setup-and-greet
              with: 
                name: "Mujakkir"