name: Docker Publish

on: 
    push:
        branches: [main]

jobs:
    frontend:
        runs-on: ubuntu-latest
        steps:
            - name: checkout the code
              uses: actions/checkout@v4
            
            - name: Build frontend Docker Image
              run: |
                docker build -t frontend-devboard-actions devboard/frontend/.
    
    backend:
        runs-on: ubuntu-latest
        steps:
            - name: checkout the code
              uses: actions/checkout@v4

            - name: Build backend Docker Image
              run: docker build -t backend-devboard-actions devboard/backend/.