name: cid
on:
  push:
    branches: [main]
jobs:
  greet:
    runs-on: ubuntu-latest
    steps: 
      - name: Check out the repository
        uses: actions/checkout@v4
      
      - name: Prints
        run: echo "Hello from GitHub Actions!"
