# Workflow
name: Hello

# on tells when the workflow should run
on:
  workflow_dispatch:

# job tells workflow what it should do
jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Say hello to everyone
        run: echo "Hello Dosto"
