name: ignore-docs 

on:
    push:
        branches:
            - main 
            - release/*
        paths-ignore:
            - '*.md'
            - 'docs/**'

jobs: 
    ignore-docs-check:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Print Ignore Message
              run: | 
                echo "Documentation-only changes were not ignored."