name: dispatch
on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the target environment'
        required: true
        type: choice
        options:
          - staging
          - production
        default: 'staging'
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: print value
        run: echo "Environment:${{ github.event.inputs.environment }}"