name: advanced

on:
  pull_request:
    types: [opened, synchronize]
    branches: [main]
jobs:
  PR-check:
    runs-on: ubuntu-latest
    steps:
      - name: prints brsnch name
        run: echo "PR check running for branch: ${{ github.head_ref }}"
      
      - name: nothing
        run: echo "add a extra line in the end"