name: run-bac

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Copy the code
        uses: actions/checkout@v4

      - name: Give permission
        run: chmod +x system_info.sh

      - name: Run the script
        run: ./system_info.sh
        shell: bash