name: run-bac

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
         - name: copy the code
           uses: actions/checkout@v4

         - name: give permission
           run: chmod +x backup.sh

         - name: run the script
           run: ./backup.sh
           shell: bash
       