name: self

on:
  workflow_dispatch:
  
jobs:
    gather:
        runs-on: [self-hosted, my-linux-runner]
        steps:
            - name: Print the hostname
              run: hostname

            - name: Print the working directory
              run: pwd

            - name: Create a file and verify it exists on your machine after the run
              run: |
                touch mujju
                ls
            